version: '3.8'

services:
  # 1. Database
  db:
    image: mysql:8.0
    container_name: video-guesser-db
    restart: always
    environment:
      MYSQL_DATABASE: videoguesser_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # Limits MySql cache
    command: --innodb-buffer-pool-size=64M

  # 2. Spring Boot
  backend:
    build:
      context: ./video-guesser-api 
    container_name: video-guesser-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/videoguesser_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - APP_ENGINE_URL=http://engine:3000

      #Limitis Java RAM usage
      - JAVA_TOOL_OPTIONS=-Xmx350m -Xms150m -XX:+UseSerialGC
    depends_on:
      - db

  # 3. Frontend (Angular + Nginx)
  frontend:
    build:
      context: ./video-guesser-ui 
    container_name: video-guesser-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
  
  # 4. Redis
  redis:
    image: redis:alpine
    container_name: youtube_guesser_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # 5. Node engine 
  engine:
    build:
      context: ./video-guesser-engine 
    container_name: video-guesser-engine
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - JAVA_BACKEND_URL=http://backend:8080 
    depends_on:
      - redis
      - backend

volumes:
  mysql_data:
  redis_data: