server {
    listen 80;

    # Roteamento do Angular (Evita o erro 404 ao atualizar a página)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # O "Proxy" de produção: repassa tudo o que for /api para o Java e liberta WebSockets!
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /ws {
            proxy_pass http://backend:8080/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade; # Essencial para manter o túnel do WebSocket aberto
            proxy_set_header Connection "upgrade";  # Diz ao servidor para transformar HTTP em WebSocket
            proxy_set_header Host $host;
        }
}
